# Generated by Django 5.0.3 on 2024-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/accounts'),
        ),
    ]
